# $FreeBSD$

PORTNAME=	electrontubes
PORTVERSION=	0.4.1
CATEGORIES=	science
MASTER_SITES=	http://www.pozsarzs.hu/sources/

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Electrontube bias calculator

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

